[window]
padding = { x = 7, y = 7 }
opacity = 0.75

[font]
normal.family      = "FiraCode"
bold.family        = "FiraCode"
italic.family      = "FiraCode"
bold_italic.family = "FiraCode"
size = 10.5

[cursor.style]
#shape = "Beam"
#blinking = "On"

[cursor]
blink_interval = 650
#thickness = 0.2

